CREATE OR REPLACE VIEW `helios-tech-interview-project.result_test.vw_weight`
AS
SELECT CAST(.15 AS FLOAT64) AS pr_weight, EXTRACT(YEAR FROM CURRENT_DATE())-1  AS pr_year UNION ALL
SELECT CAST(.15 AS FLOAT64) AS pr_weight, EXTRACT(YEAR FROM CURRENT_DATE())-2  AS pr_year UNION ALL
SELECT CAST(.15 AS FLOAT64) AS pr_weight, EXTRACT(YEAR FROM CURRENT_DATE())-3  AS pr_year UNION ALL
SELECT CAST(.15 AS FLOAT64) AS pr_weight, EXTRACT(YEAR FROM CURRENT_DATE())-4  AS pr_year UNION ALL
SELECT CAST(.15 AS FLOAT64) AS pr_weight, EXTRACT(YEAR FROM CURRENT_DATE())-5  AS pr_year UNION ALL
SELECT CAST(.10 AS FLOAT64) AS pr_weight, EXTRACT(YEAR FROM CURRENT_DATE())-6  AS pr_year UNION ALL
SELECT CAST(.08 AS FLOAT64) AS pr_weight, EXTRACT(YEAR FROM CURRENT_DATE())-7  AS pr_year UNION ALL
SELECT CAST(.04 AS FLOAT64) AS pr_weight, EXTRACT(YEAR FROM CURRENT_DATE())-8  AS pr_year UNION ALL
SELECT CAST(.02 AS FLOAT64) AS pr_weight, EXTRACT(YEAR FROM CURRENT_DATE())-9  AS pr_year UNION ALL
SELECT CAST(.01 AS FLOAT64) AS pr_weight, EXTRACT(YEAR FROM CURRENT_DATE())-10 AS pr_year